version: '3'
services:
  mongo:
    image: "mongo"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
      - MONGO_INITDB_DATABASE=nodeapp
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d